/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GithubWebhookListener': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string }> | ApiResponse<202, { status: string; message: string }> | ApiResponse<400, { status: string; message: string }>, never>
  }
    
}