import type { EventConfig } from 'motia';
import { z } from 'zod';
import { Octokit } from '@octokit/rest';
import { createPullRequest } from 'octokit-plugin-create-pull-request';

// Add the plugin to Octokit
const MyOctokit = Octokit.plugin(createPullRequest);

const inputSchema = z.object({
  repoName: z.string(),
  jobId: z.number(),
  analysis: z.object({
    rootCause: z.string(),
    filePath: z.string(),
    suggestedFix: z.string(),
    explanation: z.string()
  })
});

export const config: EventConfig = {
  name: 'CreateFixPR',
  type: 'event',
  description: 'Applies the AI fix and creates a Pull Request',
  subscribes: ['apply-fix'], // Listens to Day 3
  emits: [], // End of the line!
  flows: ['autopsy-flow'],
  input: inputSchema
};

// @ts-ignore - "Hackathon Mode" activated
export const handler = async (input: any, { logger, state }: any) => {
  const { repoName, analysis, jobId } = input;
  const [owner, repo] = repoName.split('/');

  logger.info('🩺 Surgeon is preparing to operate (creating PR)...');

  if (!process.env.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN is missing');
  }

  const octokit = new MyOctokit({
    auth: process.env.GITHUB_TOKEN,
  });

  const branchName = `autopsy/fix-${jobId}`;
  const prTitle = `fix: Auto-repair for build failure #${jobId}`;
  const prBody = `
### 🚨 Autopsy Report
**Diagnosis:** ${analysis.rootCause}

### 🧠 Proposed Fix
The AI Agent detected a failure in \`${analysis.filePath}\`.
**Reasoning:** ${analysis.explanation}

---
*Generated by CodeAutopsy Agent*
  `;

  try {
    // This magic function does EVERYTHING:
    // 1. Checks out main
    // 2. Creates a branch
    // 3. Commits the file change
    // 4. Opens the PR
    const prResponse = await octokit.createPullRequest({
      owner,
      repo,
      title: prTitle,
      body: prBody,
      head: branchName,
      base: 'main', // Ensure this matches your repo's default branch (main vs master)
      update: true,
      changes: [
        {
          files: {
            [analysis.filePath]: analysis.suggestedFix, // The file path and the new content
          },
          commit: `fix: resolve build issue in ${analysis.filePath}`,
        },
      ],
    });

    if (prResponse) {
      logger.info(`🎉 PR Created Successfully! URL: ${prResponse.data.html_url}`);
      
      // Save victory to state
      await state.set('autopsy-result', String(jobId), {
        status: 'FIXED',
        prUrl: prResponse.data.html_url
      });
      
      return { status: 'success', prUrl: prResponse.data.html_url };
    } else {
      logger.warn('⚠️ No changes needed (code might already match).');
      return { status: 'skipped' };
    }

  } catch (error: any) {
    logger.error('Failed to create PR', { error: error.message });
    throw error;
  }
};